name: divbrowse_dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9.0
  - click
  - numpy==1.21.1
  - pandas
  - flask
  - scikit-learn
  - scikit-allel
  - bioblend==0.15.0
  - pyyaml
  - zarr
  - pytables
  - waitress
  - simplejson
  - umap-learn