name: divbrowse
channels:
  - anaconda
  - bjrn
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - flask
  - scikit-allel
  - bioblend
  - pandarallel
  - pyyaml