name: Publish Python distribution to TestPyPI
on: push
jobs:
  build-n-publish:
    name: Publish Python distribution to TestPyPI
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Change version in pyproject.toml to a dev version string
      run: |
        version=$(awk -F'[ ="]+' '$1 == "version" { print $2 }' pyproject.toml)
        echo $version
        sed -i "s/$version/$version.dev0/g" pyproject.toml
        cat pyproject.toml
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        verify_metadata: false
        skip_existing: true
        verbose: true
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/